---
- name: set real ansible host variable
  set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: buster
  include_tasks: buster.yml
  when: ansible_distribution_release == "buster"

- name: bullseye
  include_tasks: bullseye.yml
  when: ansible_distribution_release == "bullseye"

- name: install autoarchive script
  copy:
    src: scratch_versioning
    dest: /usr/bin
    mode: 0755

- name: create archive directory
  file:
    path: '/home/{{  installation_os_user  }}/archive'
    state: directory
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    mode: "0644"

- name: configure autorun if file touched
  lineinfile:
    path: '/var/spool/incron/{{ installation_os_user }}'
    line: "/home/{{ installation_os_user }}/ IN_MODIFY /usr/bin/scratch_versioning $@ $#"
    regexp: '^/home/{{ installation_os_user }}/'
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    create: true
    mode: 500
  register: incron
  notify: reconfigure incron

- name: allow user to use incron
  lineinfile:
   dest: /etc/incron.allow
   state: present
   create: yes
   mode: "0644"
   line: '{{ installation_os_user }}'
